### ISSUE TITLE
Package maintenance question.

### ISSUE THREAD

**Issue by JounQin** [azz/eslint-plugin-mdx#5]
Hi, @azz .

First thanks very much for creating this plugin, and I tried it in my own project several days ago, but then I found it just could not work correctly.

It seems that it's out of maintenance about almost  one year, and the core code itself is a simple processor which actually could not parse MDX AST to ESTree AST.

So then I decide to write a new ESLint parser for MDX from scratch, it's named [eslint-mdx](https://github.com/rx-ts/eslint-mdx) with an ESLint plugin `@rxts/eslint-plugin-mdx`, it works just as expected.

So my question here is, if you don't mind and don't want to maintain this package any more, would you like to transfer the ownership of npm package? It would be great to let it be reborn and benifit the community.

My apologize for any rude requests.

Best wishes.

**Comment by azz** [comment]
Yeah I never got around to finishing this plugin, haven't been using mdx much recently so little incentive. Happy to transfer ownership of the npm name if that's possible.

**Comment by JounQin** [comment]
@azz Thanks, according to the document, it is possible.
My npm username is `jounqin`.

**Comment by azz** [comment]
I've added you as a maintainer, after a version is published let me know and I'll remove myself from it.

**Comment by azz** [comment]
Would you also mind doing a quick PR to the README here to point to your repo?

**Comment by JounQin** [comment]
Thanks, wait a moment.

**Comment by JounQin** [comment]
@azz Please review #6.

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/63022405-70207e80-bed5-11e9-81fd-e3417f37c67c.png)

@azz It seems the ownership is not working yet.

**Comment by azz** [comment]
Might take some time, you can probably try publishing anyway.

**Comment by JounQin** [comment]
@azz Thanks, that's true, I've published [v1.0.2-beta](https://www.npmjs.com/package/eslint-plugin-mdx/v/1.0.2-beta) successfully.

**Comment by azz** [comment]
Ok I've removed myself as a maintainer 👍

**Comment by azz** [comment]
Ok I'm going to archive this repository - if there's any issues feel free to contact me via email (lucas@azzola.dev) or twitter (@lucasazzola).
